name: update-repository
# <arch>-<vendor>-<os>-<env>

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  # push:
  #   tags:
  #     - "v*"

jobs:
  update-repository:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'kobyhallx/aztec_backend'
          ref: 'f96d5baed03d5058e783827d105e2c83d290c65d'
          path: '.cache/noir'

      - name: Collect Revision
        id: collect-rev
        working-directory: '.cache/noir'
        run: |
          echo "NOIR_REV_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixpkgs-22.05

      - uses: cachix/cachix-action@v12
        with:
          name: nargo-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build environment and Compile
        run: |
          nix-shell default.nix --pure --run "./build.sh"

      - name: push
        uses: actions-x/commit@v6
        with:
          message: 'tracking aztec_backend@${{ steps.collect-rev.outputs.NOIR_REV_SHORT }}'
          force: true
          name: 'kobyhallx'